---
title: "Tejon Tick Data and Visualizations"
author: "Stephanie Copeland"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(janitor)
library(tidyverse)
library(ggplot2)
#install.packages("ggstatsplot")
library(ggstatsplot)
#install.packages('PMCMRplus')
library(PMCMRplus)
```

```{r}
tejon_tick <- read.csv("tejon_all_tick_drags_09022020.csv") %>%
  clean_names() %>% 
  select(year, month, site, block, plot, total_ticks, d_occidentalis, i_pacificus, d_variabilis, other_unknown) %>% 
  drop_na()
```

```{r, better dataset made by Sam Sam}
tejon_tick_2 <- read_csv("Tejon_MixedModels_Dataset.csv")
```

```{r}
# "omit 0s to make plots look nicer, but this may not be kosher"
Full_no0 <- tejon_tick_2[which(tejon_tick_2$log_total != 0),]

ggplot(Full_no0, aes(x = plot, y = log_total, fill = plot))+
 # geom_boxplot()+
  geom_jitter(alpha = .15, width = .2, size = 3)+
  theme_bw()+
  labs(x = 'Plot', y = 'log(Total ticks) 2016 - 2019')

#ggbetweenstats(
 # data = Full_no0,
  #x = plot,
  #y = log_total
#)
```

```{r}
ggplot(Full_no0, aes(x = year, y = ipac, fill = site))+
 # geom_boxplot()+
  geom_bar(stat = "identity")+
  theme_bw()
```

```{r}
group_cols <- c("month", "site", "plot")

tejon_tick_app_1 <- Full_no0 %>% 
  select(year, month, site, plot, total, deoc, ipac, deva, other) %>% 
  group_by(across(all_of(group_cols))) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = month, values_from = n) %>% 
  add_column(January = NA) %>% 
  add_column(September = NA) %>% 
  select(site, plot, January, February, March, April, May, June, July, August, September, October, November, December) %>% 
  replace(is.na(.), 0) %>% 
  mutate(April = April/2) %>% 
  mutate(April = round(April, digits = 0))
  


```

```{r}
tejon_tick_app_2 <- Full_no0 %>% 
  select(year, month, site, plot, total, deoc, ipac, deva, other) %>% 
  group_by(across(all_of(group_cols))) %>% 
  summarize(n = n())
  


```

```{r}
ggplot(tejon_tick_app_2, aes(x = month, y = n, fill = plot))+
  geom_bar(stat = "identity")+
  theme_bw()
```

